#! /bin/bash
#  ┏━┓╻ ╻╻ ╻╻┏ ╺┳┓
#  ┗━┓┏╋┛┣━┫┣┻┓ ┃┃
#  ┗━┛╹ ╹╹ ╹╹ ╹╺┻┛

# {{{wm independent hotkeys

# terminal emulator
super + Return
  alacritty
   # $HOME/.local/bin/urxvtdc 
#rofi menus
super + p
    rofi -show drun	
super + F8

super + F9
    rofi -modi p:$HOME/.local/bin/rofi-power-menu -show p

super + b
  st -e less ~/help.txt

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd && notify-send "sxhkd reload"  

#screenshot
super + Print
    $HOME/.local/bin/rofi-screenshot

#shortcut
super + F1
   rbwmenu

super + F2
	transmenu

super + F3
	rofimoji
  
super + r
  redshift -P	
#}}}

# {{{mpc control
alt + ctrl + {Left,Down,Up,Right} 
    {mpc prev,mpc stop,mpc toggle,mpc next} && notify-send "Now playing" "$(mpc current)"
XF86AudioNext
    mpc next && notify-send "Now playing" "$(mpc current)"
XF86AudioPrev
    mpc prev && notify-send "Now playing" "$(mpc current)"
XF86AudioPlay
    mpc toggle && notify-send "Now playing" "$(mpc current)"
      #}}}

# {{{mpd control
alt + m
    [[ $(pgrep mpd) ]] && pkill mpd || mpd
    #}}}
    
#{{{Audio
XF86AudioRaiseVolume
    pamixer -i 2; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga && pamixer --get-volume | progress-notify.sh audio
    
XF86AudioLowerVolume
    pamixer -d 2; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga && pamixer --get-volume | progress-notify.sh audio

XF86AudioMute
    pamixer -t | progress-notify.sh muted
    #}}}

#{{{LockScreen
XF86ScreenSaver
  betterlockscreen -l
    #}}}

#{{{Light
XF86MonBrightnessUp
    xbacklight -inc 1 && xbacklight -get | progress-notify.sh brightness

XF86MonBrightnessDown
    xbacklight -dec 1 && xbacklight -get | progress-notify.sh brightness
#}}}

# {{{bspwm hotkeys

# quit/restart bspwm
super + shift + r
	bspc wm -r && dunstify -t 10000 "Reload BSPWM" "$(fortune)" 

super + ctrl + q
    bspc quit

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

#}}}

# {{{state/flags

# set the window state
super + {t,shift + t,@space,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

# focus/swap

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# Switch focus between the windows of the current desktop
super + {_,shift + } Tab
    bspc node -f {next,prev}.local
    #}}}

super + {w,e}
  bspc monitor -f {prev, next}
    
# {{{preselect

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel
#}}}

# {{{move and resize window

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

