#! /bin/bash
#  ┏┓ ┏━┓┏━┓╻ ╻┏┳┓
#  ┣┻┓┗━┓┣━┛┃╻┃┃┃┃
#  ┗━┛┗━┛╹  ┗┻┛╹ ╹

intern=LVDS1
extern=VGA1
 if [[ $(xrandr -q | grep "$extern connected") ]];
 then
    xrandr --output "$extern" --right-of "$intern" --auto
    bspc monitor $intern -d 1 2 3 4 5
    bspc monitor $extern -d 6 7 8 9 10
else
    xrandr --output "$extern" --off
    bspc monitor -d 1 2 3 4 5 6
 fi

xsetroot -cursor_name left_ptr

# {{{bspc config
bspc config border_width                2
bspc config focused_border_color        "#313244"
bspc config normal_border_color         "#1E1E2E" 
bspc config window_gap                  4
bspc config focus_follows_pointer       true

bspc config split_ratio                 0.5
bspc config gapless_monocle             true
bspc config borderless_monocle          true #}}}

#trigger sxhkd#{{{
pgrep -x sxhkd > /dev/null || sxhkd &
#}}}

#setting wallpaper#{{{
feh --bg-fill   ~/Pictures/wallpapers/mandelbrot_full_green.png &
#}}}

# {{{bspc rule
bspc rule -a Gimp desktop='^4' follow=on state=floating
bspc rule -a zathura state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a feh state=floating
bspc rule -a KeePassXC desktop='^6' follow=on state=floating focus=on
bspc rule -a mpv state=fullscreen focus=on
bspc rule -a Arandr state=floating
bspc rule -a qutebrowser desktop='^2' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a TelegramDesktop desktop='^5' follow=on
bspc rule -a Soffice desktop='^3' follow=on
bspc rule -a Inkscape desktop='^4' follow=on #}}}

#Autostart#{{{

xrdb .Xresources
## polybar
pkill polybar
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload &
  done
else
  polybar --reload &
fi
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
## dunst
pkill dunst; dunst &
picom --config ~/.config/picom/picom.conf & #picom

# pkill unclutter;unclutter -root & #autohide cursor
# pkill conky;$HOME/.local/bin/start_conky & #conky
pkill xbanish; xbanish &
xset s 240 60; xset dpms 301;xss-lock -n ~/.local/bin/dim-screen.sh -- betterlockscreen --lock &
# xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
pkill usermount; usermount &
pkill battery.sh; $HOME/.local/bin/battery.sh
pkill progress-notify.sh; $HOME/.local/bin/progress-notify.sh
setxkbmap -option grp:alt_shift_toggle us,ara
#}}}
