#!/bin/bash

CONFIG_FILE="$HOME/.config/waybar/config.jsonc"
STYLE_FILE="$HOME/.config/waybar/style.css"

trap "killall waybar" EXIT

while true; do
    waybar -c "$CONFIG_FILE" -s "$STYLE_FILE" &
    inotifywait -e create,modify "$CONFIG_FILE" "$STYLE_FILE"
    killall waybar
done
